# ========================
# TOMCAT
# ========================
server:
  tomcat:
    additional-tld-skip-patterns: '*.jar'
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# ========================
# SPRING
# ========================
logging:
  level:
    org.springframework: ${LOG_LEVEL:INFO} 
    ch.so.agi: ${LOG_LEVEL_APP:DEBUG} 

spring:
  web:
    resources:
        static-locations: classpath:/launcherDir/,classpath:/public/
    #resources:
     #   static-locations: classpath:/launcherDir/,classpath:/public/
    devtools:
        restart:
            additional-exclude: launcherDir/**
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:300}MB
      max-request-size: ${MAX_FILE_SIZE:300}MB

management:
  health:
    probes:
      enabled: true
    endpoint:
      health: 
        show-details: always
        livenessState:
          enabled: true
        readinessState:
          enabled: true

# spring:
#     profiles:
#         active: test 

# ========================
# APPLICATION
# ========================   
  
app:
    myVar: ${VAR:defaultValue}
    connectTimeout: ${connectTimeout:5000}
    readTimeout: ${readTimeout:5000}
    workDirectory: ${WORK_DIRECTORY:/tmp/}
    folderPrefix: ${FOLDER_PREFIX:ilivalidatorws_}