# ========================
# TOMCAT
# ========================
server:
  tomcat:
    threads:
      max: ${TOMCAT_THREADS_MAX:20}
    accept-count: ${TOMCAT_ACCEPT_COUNT:100}
    max-connections: ${TOMCAT_MAX_CONNECTIONS:500}
    additional-tld-skip-patterns: '*.jar'
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#default-servlet-registration
# https://stackoverflow.com/questions/64822250/illegalstateexception-after-upgrading-web-app-to-spring-boot-2-4
  servlet:
    register-default-servlet: true

# ========================
# SPRING
# ========================
logging:
  level:
    org.springframework: ${LOG_LEVEL:INFO} 
    com.zaxxer.hikari: ${LOG_LEVEL_DB_CONNECTION_POOL:INFO} 
    ch.so.agi: ${LOG_LEVEL_APPLICATION:DEBUG} 

spring:
  web:
    resources:
        static-locations: classpath:/launcherDir/,classpath:/public/
    #resources:
     #   static-locations: classpath:/launcherDir/,classpath:/public/
    devtools:
        restart:
            additional-exclude: launcherDir/**
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:300}MB
      max-request-size: ${MAX_FILE_SIZE:300}MB

  datasource:
    hikari.maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
    url: ${JDBC_URL:jdbc:sqlite:/Users/stefan/tmp/jobrunr_db.sqlite}
    #url: ${JDBC_URL:jdbc:sqlite:/tmp/jobrunr_db.sqlite}
    #url: ${JDBC_URL:jdbc:h2:/Users/stefan/tmp/jobrunr_db}
    #username: ${JDBC_USER:admin}
    #password=${JDBC_PWD:admin}
#    h2:
#      console:
#        enabled: false

management:
  health:
    probes:
      enabled: true
    endpoint:
      health: 
        show-details: always
        livenessState:
          enabled: true
        readinessState:
          enabled: true

# spring:
#     profiles:
#         active: test 

# ========================
# APPLICATION
# ========================   
  
org:
  jobrunr:
    background-job-server:
      enabled: ${JOBRUNR_SERVER_ENABLED:true}
      worker_count: ${JOBRUNR_WORKER_COUNT:1} 
      poll-interval-in-seconds: ${JOBRUNR_POLL_INTERVAL:10}
    dashboard:
      enabled: ${JOBRUNR_DASHBOARD_ENABLED:true}
      username: ${JOBRUNR_DASHBOARD_USER:admin}
      password: ${JOBRUNR_DASHBOARD_PWD:admin}
  
app:
  myVar: ${VAR:defaultValue}
  connectTimeout: ${CONNECT_TIMEOUT:5000}
  readTimeout: ${READ_TIMEOUT:5000}    
  docBase: ${DOC_BASE:/tmp/}
  configDirectoryName: ${CONFIG_DIRECTORY_NAME:config}
  unpackConfigFiles: ${UNPACK_CONFIG_FILES:true}
  #workDirectory: ${WORK_DIRECTORY:/ch.so.agi.ilivalidator}
  workDirectory: ${WORK_DIRECTORY:/tmp/}
  folderPrefix: ${FOLDER_PREFIX:ilivalidatorws_}
  restApiEnabled: ${REST_API_ENABLED:true}
  cleanerEnabled: ${CLEANER_ENABLED:true}
  storageService: ${STORAGE_SERVICE:local}
  #storageService: ${STORAGE_SERVICE:s3}
  awsAccessKey: ${AWS_ACCESS_KEY_ID}
  awsSecretKey: ${AWS_SECRET_ACCESS_KEY}
