name: CI/CD

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:

  build-jvm:
    env:
      DOCKER_ACCOUNT: sogis
      DOCKER_REPO: ilivalidatorws
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}} 
      BUILD_NUMBER: ${{ github.run_number }}
      VERSION: 2.0.${{ github.run_number }}

    runs-on: ubuntu-latest

    steps:

      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'
          cache: 'maven'

      - name: Test and build Jar
        run: |
          ./mvnw -Penv-prod clean package -DexcludedGroups="docker"
          ls -la ilivalidatorws-server/target

      - name: Set up QEMU for amd64 and arm64
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Single-platform build (for Docker image tests)
        uses: docker/build-push-action@v2
        with:
          context: ilivalidatorws-server
          file: ilivalidatorws-server/Dockerfile.jvm
          tags: ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}
          load: true
          pull: true 

      - name: List Docker images
        run: |
          docker images

      - name: Test Docker image
        run: ./mvnw test -Dgroups="docker"

      - name: Login to Docker Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}

      - name: Multi-platform build and push to Docker Container Registry
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: ilivalidatorws-server
          file: ilivalidatorws-server/Dockerfile.jvm
          labels: ${{ steps.meta.outputs.labels }}
          pull: true
          push: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}
          tags: |
            ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:${{ env.VERSION }}
            ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:2.0
            ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:2
            ghcr.io/${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:latest
            ghcr.io/${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:${{ env.VERSION }}
            ghcr.io/${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:2.0
            ghcr.io/${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:2
